FROM jtetris.base:latest

RUN mkdir -p /home/jtetris
WORKDIR /home/jtetris
RUN git clone https://github.com/jmedina2099/JTetris2022.git

# COMPILATION
WORKDIR /home/jtetris/JTetris2022/src/main/angular
RUN npm i

EXPOSE 2222 4200

WORKDIR /home/jtetris/JTetris2022
ENTRYPOINT ["./run-angular"]
