FROM openjdk:11

# Install maven
RUN apt-get update  
RUN apt-get install -y maven
# RUN apt-get install -y nodejs npm
RUN apt-get install -y rabbitmq-server

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash
RUN apt update -y
RUN apt install nodejs -y

RUN npm install -g yarn
RUN npm install -g @angular/cli
RUN npm install -g lite-server
