FROM jtetris.base:latest

RUN mkdir -p /home/jtetris
WORKDIR /home/jtetris
RUN git clone https://github.com/jmedina2099/JTetris2022.git

WORKDIR /home/jtetris/JTetris2022/src/main/react
RUN npm i

EXPOSE 3000

WORKDIR /home/jtetris/JTetris2022
ENTRYPOINT ["./run-front-react"]
