FROM jtetris.base:latest

RUN mkdir -p /home/jtetris
WORKDIR /home/jtetris
RUN git clone https://github.com/jmedina2099/JTetris2022.git

EXPOSE 5672

WORKDIR /home/jtetris/JTetris2022
ENTRYPOINT ["./run"]
