FROM jtetris.base:latest

RUN mkdir -p /home/jtetris
WORKDIR /home/jtetris
RUN git clone https://github.com/jmedina2099/JTetris2022.git

WORKDIR /home/jtetris/JTetris2022
RUN mvn clean package

WORKDIR /home/jtetris/JTetris2022/src/main/rabbit-server
RUN npm i

RUN mkdir -p /etc/rabbitmq/certs
COPY certs/* /etc/rabbitmq/certs/

COPY config/rabbitmq.conf /etc/rabbitmq/

EXPOSE 2222 5671 4000 8080

WORKDIR /home/jtetris/JTetris2022
ENTRYPOINT ["./run-rabbitmq-server"]
