#!/bin/bash

(service rabbitmq-server restart && (./run-back &) && (./run-rabbitmq-server &) );

for args in "$@"
do
	if [ "$1" == "angular" ]; then
		./run-front-angular;
	fi
	if [ "$1" == "react" ]; then
		./run-front-react;
	fi
done
