#!/bin/bash

echo "Adding hostname to /etc/hosts"
echo "127.0.0.1       jtetrisappback.azurewebsites.net" >> /etc/hosts

echo "Starting ssh server..."
service ssh restart

echo "Starting postgresql server..."
service postgresql restart

echo "Creating user and db..."
su - postgres -c "psql -c \"CREATE USER jmedina WITH ENCRYPTED PASSWORD 'jmedina'\"";
su - postgres -c "psql -c \"CREATE DATABASE jtetris\"";
su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE jtetris TO jmedina\"";

echo "****************** Running spring-boot.. *********************"
java -jar target/jtetris-0.0.1-SNAPSHOT.jar
