#!/bin/bash

echo "Adding hostname to /etc/hosts"
echo "127.0.0.1       jtetrisappreact.azurewebsites.net" >> /etc/hosts

echo "Starting ssh server..."
service ssh restart

echo "Dispatching react..."
cd src/main/react/

# DEV
# npm start

# PROD
npm run build
serve -s build
